-- Cria tabela tb_anexo
CREATE TABLE ppi_curso.tb_anexo (
    id_anexo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_anexo VARCHAR(255) NOT NULL,
    desc_anexo TEXT,
    id_asset BIGINT NOT NULL,
    FOREIGN KEY (id_asset) REFERENCES ppi_curso.tb_asset (id_asset)
    ON DELETE RESTRICT ON UPDATE CASCADE
);