CREATE TABLE IF NOT EXISTS ppi_curso.tb_avaliacao_versao_curso (
    id_avaliacao                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario                  BIGINT NOT NULL,
    id_versao_curso_pedagogico  BIGINT NOT NULL,
    nota                        SMALLINT NOT NULL CHECK (nota BETWEEN 1 AND 5),
    comentario                  TEXT NULL CHECK (LENGTH(comentario) <= 500),
    dt_avaliacao                TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_usuario_versao UNIQUE (id_usuario, id_versao_curso_pedagogico),
    
    CONSTRAINT fk_avaliacao_usuario FOREIGN KEY (id_usuario)
      REFERENCES ppi_seg.tb_usuario(id_usuario),
    
    CONSTRAINT fk_avaliacao_versao  FOREIGN KEY (id_versao_curso_pedagogico)
      REFERENCES ppi_curso.tb_versao_curso_pedagogico(id_versao_curso_pedagogico)
);


CREATE INDEX IF NOT EXISTS tb_avaliacao_versao_curso ON ppi_curso.tb_avaliacao_versao_curso (id_versao_curso_pedagogico);
CREATE INDEX IF NOT EXISTS idx_avaliacao_usuario ON ppi_curso.tb_avaliacao_versao_curso (id_usuario);
