CREATE TABLE IF NOT EXISTS ppi_curso.tb_inscricao_curso (
    id_inscricao        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario          BIGINT NOT NULL,
    id_curso_pedagogico BIGINT NOT NULL,
    dt_inscricao        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ind_ativo           BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_usuario_curso 
        UNIQUE (id_usuario, id_curso_pedagogico),

    CONSTRAINT fk_inscricao_usuario 
        FOREIGN KEY (id_usuario)
        REFERENCES ppi_seg.tb_usuario(id_usuario),

    CONSTRAINT fk_inscricao_curso 
        FOREIGN KEY (id_curso_pedagogico)
        REFERENCES ppi_curso.tb_curso_pedagogico(id_curso_pedagogico)
);


CREATE INDEX IF NOT EXISTS idx_inscricao_usuario ON ppi_curso.tb_inscricao_curso (id_usuario);
CREATE INDEX IF NOT EXISTS idx_inscricao_curso ON ppi_curso.tb_inscricao_curso (id_curso_pedagogico);
