-- Cria tabela tb_anexo_aula
CREATE TABLE ppi_curso.tb_anexo_aula (
    id_anexo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tit_anexo VARCHAR(255) NOT NULL,
    desc_anexo TEXT,
    id_arquivo BIGINT NOT NULL,
    FOREIGN KEY (id_arquivo) REFERENCES ppi_curso.tb_arquivo (id_arquivo)
);