/* =============================================================
   06 · CRIAÇÃO DA TABELA ANEXO_AULA
   =============================================================*/
BEGIN;

/*--------------------------------------------------------------
  1 · Criar tabela se não existir
  --------------------------------------------------------------*/
CREATE TABLE IF NOT EXISTS ppi_curso.tb_anexo_aula (
    id_anexo   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tit_anexo  VARCHAR(255) NOT NULL,
    desc_anexo TEXT
);

/*--------------------------------------------------------------
  2 · Adicionar coluna + FK para AULA
  --------------------------------------------------------------*/
ALTER TABLE ppi_curso.tb_anexo_aula
    ADD COLUMN IF NOT EXISTS id_aula BIGINT;

COMMENT ON COLUMN ppi_curso.tb_anexo_aula.id_aula
    IS '🔗 Aula à qual o anexo pertence';

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint
               WHERE conname = 'fk_anexo_aula_aula') THEN
        ALTER TABLE ppi_curso.tb_anexo_aula
          DROP CONSTRAINT fk_anexo_aula_aula;
    END IF;
    ALTER TABLE ppi_curso.tb_anexo_aula
        ADD CONSTRAINT fk_anexo_aula_aula
        FOREIGN KEY (id_aula)
        REFERENCES ppi_curso.tb_aula(id_aula)
        ON DELETE CASCADE
        ON UPDATE NO ACTION;
    COMMENT ON CONSTRAINT fk_anexo_aula_aula ON ppi_curso.tb_anexo_aula
        IS '🔗 Anexo → Aula (cascade na exclusão)';
END $$;

/*--------------------------------------------------------------
  3 · Adicionar coluna + FK para ARQUIVO
  --------------------------------------------------------------*/
ALTER TABLE ppi_curso.tb_anexo_aula
    ADD COLUMN IF NOT EXISTS id_arquivo BIGINT;

COMMENT ON COLUMN ppi_curso.tb_anexo_aula.id_arquivo
    IS '🔗 Arquivo físico associado (1:1)';

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint
               WHERE conname = 'fk_anexo_aula_arquivo') THEN
        ALTER TABLE ppi_curso.tb_anexo_aula
          DROP CONSTRAINT fk_anexo_aula_arquivo;
    END IF;
    ALTER TABLE ppi_curso.tb_anexo_aula
        ADD CONSTRAINT fk_anexo_aula_arquivo
        FOREIGN KEY (id_arquivo)
        REFERENCES ppi.tb_arquivo(id_arquivo)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION;
    COMMENT ON CONSTRAINT fk_anexo_aula_arquivo ON ppi_curso.tb_anexo_aula
        IS '🔗 Anexo → Arquivo (sem cascata de exclusão)';
END $$;

/*--------------------------------------------------------------
  4 · UNIQUE(id_arquivo) ⇒ garante 1:1
  --------------------------------------------------------------*/
CREATE UNIQUE INDEX IF NOT EXISTS uk_anexo_aula_id_arquivo
    ON ppi_curso.tb_anexo_aula(id_arquivo);

COMMENT ON INDEX uk_anexo_aula_id_arquivo
    IS '⚙️  Cada Arquivo pode ser usado em apenas 1 AnexoAula';

COMMIT;
